name: Create release on tag push

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get release body
        run: |
          echo "release_body=$(cat CHANGELOG.md)" >> "$GITHUB_ENV"

      - name: Zip up the files
        run: zip -r bg3-mod-profiles-for-linux.zip util bg3overlay bg3switch LICENSE README.md

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.1"

      - name: Draft release
        uses: https://gitea.com/actions/release-action@main
        with:
          body: ${{ env.release_body }}
          files: |-
            bg3-mod-profiles-for-linux.zip
          draft: true
          api_key: "${{ secrets.RELEASE_TOKEN }}"
